export { db } from '@/lib/storage/db';
export { getAllNovels, getNovel, createNovel, updateNovel, deleteNovel, getOrCreateDefaultNovel } from '@/lib/storage/novels';
export { getChapters, getChapter, createChapter, addChapter, updateChapter, deleteChapter, reorderChapters } from '@/lib/storage/chapters';
export { getSnapshots, createSnapshot, updateSnapshotLabel, deleteSnapshot } from '@/lib/storage/snapshots';
export { exportBackup, importBackup, upgradeBackup } from '@/lib/storage/backup';
export { getCommentThreads, upsertCommentThread, saveAllCommentThreads, deleteCommentThread } from '@/lib/storage/comments';
export { getStoryBlueprint, upsertStoryBlueprint, deleteStoryBlueprint } from '@/lib/storage/blueprints';
export { upsertGoalTrendSnapshot, getGoalTrendSnapshots } from '@/lib/storage/goalTrends';
export type { GoalTrendSnapshot } from '@/lib/storage/goalTrends';
export { exportDhproj, importDhproj } from '@/lib/storage/dhproj';
export type { DhprojExportOptions } from '@/lib/storage/dhproj';
export { clearAllData, replaceNovelData, secureWipeIntegrationArtifacts } from '@/lib/storage/dataManagement';
export { mergeImportedSettings, mergeImportedIntegrations, isCharacterEntity, isWorldEntry, isProgressData, mergeProgressData } from '@/lib/storage/migrations';
